# Generated by Django 5.1.6 on 2025-04-17 19:49
#pylint: disable=missing-module-docstring
#pylint: disable=missing-class-docstring

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CS4300_backend', '0002_allergen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='allergen',
            old_name='Allergen',
            new_name='allergen',
        ),
    ]
