name: Code Review with ChatGPT

on:
  pull_request:
    branches:
      - main
      - develop

jobs:
  review:
    permissions:
      pull-requests: write
      issues: read
      contents: read
      actions: write
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Code Review with ChatGPT
        uses: cirolini/genai-code-review@v2
        with:
          openai_api_key: ${{ secrets.OPENAI_API_KEY }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          github_pr_id: ${{ github.event.number }}
