name: Run Django Tests with Coverage

on:
  pull_request:
    branches:
      - main
      - develop

jobs:
  coverage:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write  # Allow write access to pull requests
      issues: read          # Read access to issues

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-cov django djangorestframework pytest-django

    - name: Set DJANGO_SETTINGS_MODULE environment variable
      run: echo "DJANGO_SETTINGS_MODULE=CS4300_django_server.settings" >> $GITHUB_ENV

    - name: Run tests with coverage
      run: pytest --cov=. --cov-report=xml

    - name: Post coverage comment
      uses: marocchino/sticky-pull-request-comment@v2
      with:
        path: ./coverage.xml
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }